console.log("Tous les Pokemons");
console.log(Pokemon.all_pokemons);
console.log("-------------------");
console.log("Pokemon 1 (Bulbasaur)");
console.log(Pokemon.all_pokemons[1].toString());
console.log("-------------------");
console.log("Pokemons Grass");
console.log(getPokemonsByType('Grass'))
console.log("-------------------");
console.log("Attaque 210 (Wing Attack)");
console.log(Attack.all_attacks[210].toString());
console.log("-------------------");
console.log("Type Bug");
console.log(Type.all_types['Bug'].toString());
console.log("-------------------");
console.log("Attaques de type water");
console.log(getAttacksByType('Water'));
console.log("-------------------");
console.log("liste des pokemns trié par types et noms");
console.log(sortPokemonsByTypeThenName());